name: 'Build image and push to Docker hub'

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: zkautomate
  DOCKER_HUB_REPO: spilo

jobs:
  build-deploy-pg16-2-18-2:
    name: Build and deploy pg-16 timescaledb-2.18.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile.pg16-2.18.2
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:16-2.18.2

  build-deploy-pg17-2-18-2:
    name: Build and deploy pg-17 timescaledb-2.18.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile.pg17-2.18.2
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:17-2.18.2
